[package]
name = "osc52"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
base64 = "0.21.2"
clap = { version = "4.3.21", features = ["derive", "env"] }
termios = "0.3.3"
